sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew test integrationTest --stacktrace

after_success:
- ./gradlew jacocoTestReport coveralls
